# Image: tapis/tapipy-tests
# Build: docker build -t tapis/tapipy-tests -f Dockerfile-tests .
# Run it:
#    docker run -it --rm tapis/tapipy-tests
# Try it:
#    docker run -it --rm tapis/tapipy bash
#    docker run -it --rm -v $(pwd)/test/resource_examples:/home/tapis/resource_examples tapis/tapipy bash
#    docker run -it --network tenants-api_tenants --rm tapis/tapipy bash

from python:3.7

# Moving files
ADD tests/tapipy-tests.py /home/tapis/tapipy-tests.py
ADD tests/configschema.json /home/tapis/configschema.json
ADD tests/config-dev-develop.json /home/tapis/config.json

# Add tapipy files and build with Poetry build.
ADD . /home/tapis/tapipy-install-dir
RUN pip install -r /home/tapis/tapipy-install-dir/requirements.txt
WORKDIR /home/tapis/tapipy-install-dir
RUN poetry build
WORKDIR /home/tapis/tapipy-install-dir/dist
RUN pip install *.whl
WORKDIR /home/tapis

# Install tapisservice to do testing with service account as we do.
RUN pip3 install tapisservice


# Testing
ENTRYPOINT ["pytest", "--verbose", "/home/tapis/tapipy-tests.py"]