# Image: tapis/tapipy-tests
# Build: docker build -t tapis/tapipy-tests -f Dockerfile-tests .
# Run it:
#    docker run -it --rm -e username=user -e password=pass tapis/tapipy-tests
# Try it:
#    docker run -it --rm tapis/tapipy-tests bash
#    docker run -it --rm -v $(pwd)/test/resource_examples:/home/tapis/resource_examples tapis/tapipy-tests bash
#    docker run -it --rm --network tenants-api_tenants tapis/tapipy-tests bash

FROM python:3.7

# Upgrade pip
RUN python -m pip install --upgrade pip

# Moving files
ADD tests/tapipy-tests.py /home/tapis/tapipy-tests.py
#ADD tests /home/tapis/tests

# Add tapipy files and build with Poetry build.
ADD . /home/tapis/tapipy-install-dir
RUN pip install -r /home/tapis/tapipy-install-dir/requirements.txt
WORKDIR /home/tapis/tapipy-install-dir
RUN poetry build
WORKDIR /home/tapis/tapipy-install-dir/dist
RUN pip install *.whl
WORKDIR /home/tapis

# Testing
ENTRYPOINT ["pytest", "--verbose", "/home/tapis/tapipy-tests.py"]
#ENTRYPOINT [ "/home/tapis/tests/run.sh" ]