name: Workflows CI

on:
  push:
    tags: [ v*.*.* ]
    branches: [ dev, staging, main]
  pull_request:
    branches: [ dev, staging, main]

jobs:
  Unit_Tests:
    name: Unit_Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup_Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run_Unit_Tests
        run: ./tests/run.sh